### PR TITLE
Adds support for "renamecreate" where the currently processed file gets

### PR DESCRIPTION
**Pull request by bobtiernay-okta**
Adds support for "renamecreate" semantics where the currently processed file gets renamed and the original file gets recreated. This is the behavior of certain logfile rollers such as `TimeBasedRollingPolicy` in Java's Logback library.

Addesses https://github.com/bgreenlee/pygtail/issues/36.

### CODE REVIEW

**Comment by bobtiernay-okta** [comment]
@bgreenlee Seems like CI build is failing due to an unrelated issue:

https://travis-ci.org/bgreenlee/pygtail/jobs/275943364
```
0.35s$ if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors unittest2; fi
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...
no such option: --use-mirrors
```
Thoughts on how to resolve?

**Comment by bgreenlee** [comment]
Hey, I know it's been a while, and you've probably moved on from this, but I'm trying to figure out how to write a test for your change and could use some guidance.

**Comment by bobtiernay-okta** [comment]
Basically we need to simulate "at the end of current file which has been renamed". That means having pigtail be current and then renaming the file it is currently processing. Make sense?

**Comment by bgreenlee** [comment]
I guess I don't see how that differs from any other rotation. I can't seem to write a failing test. Here's what I have right now:

```
def test_renamecreate(self):
    """
    Tests "renamecreate" semantics where the currently processed file gets renamed and the
    original file gets recreated. This is the behavior of certain logfile rollers such as
    TimeBasedRollingPolicy in Java's Logback library.
    """
    new_lines = ["4\n5\n", "6\n7\n"]
    pygtail = Pygtail(self.logfile.name)
    pygtail.read()
    os.rename(self.logfile.name, "%s.2018-03-10" % self.logfile.name)
    # append will recreate the original log file
    self.append(new_lines[0])
    self.append(new_lines[1])
    pygtail = Pygtail(self.logfile.name)
    self.assertEqual(pygtail.read(), ''.join(new_lines))
```

**Comment by bobtiernay-okta** [comment]
Are we sure `self.append` is writing to the new file and not the old file that was renamed?

**Comment by bgreenlee** [comment]
[Yes](https://github.com/bgreenlee/pygtail/blob/master/pygtail/test/test_pygtail.py#L31).

**Comment by bgreenlee** [comment]
Ok, I think I've got it. I just had to remove the `pygtail = Pygtail(self.logfile.name)` on the second-to-last line.

**Comment by bgreenlee** [comment]
Ok, I've merged it. Thanks!

**Comment by bobtiernay-okta** [comment]
@bgreenlee YTMND!

**Pull request closed without merging**
