### PR TITLE
Adding possibility to set the encoding 

### PR DESCRIPTION
**Pull request by Robert-Lebedeu**
I have seen that there is another pull request which tries to add this feature but it doesn't pass all the tests. I tried to improved and now it should pass all tests.

### CODE REVIEW

**Comment by bgreenlee** [comment]
Looks like a good addition, thanks. Is there a good way to add a test for this?

**Comment by beyondmeat** [comment]
sad that this died :(

**Comment by Spud1001** [comment]
@bgreenlee can we merge this please? I'm happy to contribute if there are further changes

**Comment by bgreenlee** [comment]
Merging

**Pull request closed without merging**
